services:
  service_1:
    build:
      context: ./service_1
    container_name: service_1
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8001 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  service_2:
    build:
      context: ./service_2
    container_name: service_2
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8002/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      service_1:
        condition: service_healthy
      service_2:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
